print("vivek")
print("dev")
print("i like samosa")
print("im software developer")
print("vivek")
print("dev")
print("i like samosa")
print("im software developer")
print("vivek")
print("dev")
print("i like samosa")
print("im software developer")
print("vivek")
print("dev")
print("i like samosa")
print("im software developer")